### ISSUE TITLE
Documentation needed on loading external files

### ISSUE THREAD

**Issue by clhenrick** [willamesoares/learn-d3#1]
Hi, just tried using your boilerplate and am noticing that GET requests for data files, such as CSV and JSON, will fail if they aren't in the `dist/` directory. You may want to note that in the documentation as it's so common to load external data in a file with D3. From my personal experience with front end build tools, data files tend not to live in the directory that contains compiled code.

I personally tend to set up Webpack so that I can load files from a `data` directory that resides in the root of the repo. The `copy-webpack-plugin` can copy such directories and files to `dist` for production configuration.

Thanks for this setup btw!

**Comment by willamesoares** [comment]
Hi @clhenrick! I appreciate your comment. That is something I missed and I'm glad you pointed it out.

As you suggested, I included a step in the webpack configuration file so the data files will be copied to the `dist` folder. When doing that I also thought about creating a more generic step and including an `assets` folder in which I would consider images and other kinds of static files as well. However, as this was intended to be a boilerplate focused only on setting up a basic environment so people can start playing with D3, I realized I shouldn't go that far and instead keep it simple.

As you mentioned, and I agree, loading external data is a common thing in D3 projects, so adding this step is surely a valid point in a boilerplate.

Here are the relevant commits:
[Add webpack configuration for data folder](https://github.com/willamesoares/learn-d3/commit/400f7fd0d1f8b3c6dee0ac139de7837f3a9a6c8b)
[Add documentation on loading external data](https://github.com/willamesoares/learn-d3/commit/73271ec5e83c1c01aa9d2f9b753b8fd3f8ad001c)
